package com.learning.collections.sets;

public final class Car implements Comparable<Car> {
    private final String make;
    private final String model;
    private final Integer price; //use Integer for using it the overriden equals method later (or you can use == to compare primitive types)
    //those should be final in order to avoid changing the hashCode

    public Car(String make, String model, Integer price) {
        this.make = make;
        this.model = model;
        this.price = price;
    }

    public String getMake() {
        return make;
    }

    public String getModel() {
        return model;
    }

    public Integer getPrice() {
        return price;
    }

    //both equals and hashCode can be autogenerated or implemented manually like this:
    @Override
    public boolean equals(Object obj) {
        if (this == obj) {
            return true;
        }
        if (obj == null || this.getClass() != obj.getClass()) {
            return false;
        }
        Car car = (Car) obj; // cast the passed object to the Car object to use it for comparison
        if (!this.make.equals(car.getMake())) {
            return false;
        } else if (!this.model.equals(car.getModel())) {
            return false;
        } else if (!this.price.equals(car.getPrice())) {
            return false;
        } else {
            return true;
        }
    }

    @Override
    public int hashCode() {
        int result = make.hashCode();
        result += 31 * model.hashCode();
        result += 31 * price.hashCode();
        return result;
    }

    //tree sets will be sorted by price
    @Override
    public int compareTo(Car car) {
        if (price < car.getPrice()) {
            return -1;
        }
        if (price > car.getPrice()) {
            return +1;
        }
        return 0;
    }

    @Override
    public String toString() {
        return make + " " + model + " - $" + price + " a day";
    }
}
